version:  '3'
services:
  ot6:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8080:8080"
    restart:  always
    container_name: mercado-livre
    image:  ml_ot6
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL:  jdbc:mysql://db_mercado_livre:3306/ml?&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zupper
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - backend
    
  db:
    image:  mysql
    ports:
      - "3308:3306"
    restart:  always
    container_name: db_mercado_livre
    environment:
      MYSQL_DATABASE: ml
      MYSQL_ROOT_PASSWORD:  zupper
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: 
    driver: bridge
